= SREとは
:revnumber: 1.0.0
:revdate: 2026-03-11
:toc: left
:toclevels: 3
:sectnums:

SREは、サイト信頼性エンジニアリングのこと。開発担当と運用担当が連携し、システムの信頼性を高めて安定稼働を実現しながら、
新機能の追加やサービス改善を円滑に行い、UXを高めることを目指す。
現代では、信頼性と作業効率を両立したシステム開発が求められている。定型作業の自動化や各種指標の計測を行うSREの導入によって、
企業競争力のさらなる強化につながる。
運用タスクの自動化とエラーバジェットの活用により、システムの信頼性とサービスの成長の両立を実現。

== SREとDevOpsは何が違うのか

* SREの概念
** 開発と運用を組み合わせたDevOpsと混同されがちだが、両者の違いは「class SRE implements DevOps」という考え方。
これはオブジェクト指向プログラミングになぞらえた表現で、DevOpsで示された抽象的な概念を、SREで具体的に実践するという意味。
つまり、DevOpsでは開発担当と運用担当が一体化して業務の効率化を図ることを目指すのに対して、SREでは、自動化ツールで運用タスクの
処理速度を上げつつ、システムの信頼性を高めることを目指す。

== SREを実践する際に注意すべきこと

* SREの「本来の目的」を理解する
** SREには「信頼性」をシステムの重要機能の一つとして位置付けているという特徴がある。そこで信頼性を高めるために、エラーの発生を限りなくゼロに
近づけるなど、理想的な目標を設定することに固執して、かえって現場の混乱を招く結果に陥っている場合がある。
* SREの本来の目的は単純な信頼性の向上ではなく、極端に高い指標を追いかけることでもない。ユーザーが一定の満足度を得られるサービス運用を
実現しながら、開発のライフサイクルを高速化し、開発運用のアジリティを高めること。あくまでも、高すぎない目標値の下でトイルの自動化を進め、
システムの改善とサービスレベルの向上におけるトレードオフに挑むことが大切。
* このようなSREの本来の目的を踏まえつつ、サービスレベルの評価を行う必要がある。

== SREの実践に欠かせない要素

* SREの4要素
** CUJ（購買体験）
*** ユーザーにとって重要度が高く、ビジネスへの影響が大きいポイントをモデル化。例：ECサイトにおけるログイン/商品の検索/カートへの追加/決済
** SLI（サービスレベル指標）
*** 定量的に測定できる、システムの品質を測定するための指標。例：稼働率/エラー率/スループット/応答時間
** SLO（サービスレベル目標）
*** SLIで選定した指標の目標数値。許容可能な最低限のレベルに設定。例：月次稼働率が99.00%以上
** SLA（サービスレベル契約）
*** サービスの品質に関する契約。サービス提供者と顧客の権利と義務を明確にする。例：ECサイト構築サービスで月次稼働率が99.00%を下回った場合には返金による
補償の実施
* CUJ：ビジネス視点で重要な箇所に焦点を当てたカスタマージャーニー
** 製品・サービスの発見から購入後の行動に至るまで、ユーザーがたどる一連の購買体験を「カスタマージャーニー」と呼ぶ。
CUJは、そのカスタマージャーニーの中でも特にビジネスの観点で重要な部分に焦点を当てたもので、ユーザーが頻繁に行う作業や重要な操作が選定される。
分析手順としては、まず分析目標の設定やペルソナ設計、データ収集、ユーザーのセグメンテーションなどの下準備を行う。そして、タッチポイント（企業との接点）とユーザーの感情などをマッピングして視覚化し、どの体験がユーザーにとって重要度の高いものなのか、ビジネスの観点で影響が大きいのかを検討し、モデル化する。ここでモデル化された行動が、当該サービスにおけるサービスレベルの観測ポイント（SLI：サービスレベル指標）となる。
* SLI：サービスレベル指標
** SLIは「サービスレベル指標」と呼ばれ、システムの品質を測定するための指標のこと。数値やパーセンテージなどで定量的に測定できることが重要。用いられる
指標の種類はサービスによって異なる、一般的には「稼働率」「エラー率」「スループット」「応答時間」といったメトリクスが用いられる。
SLIの設定時には、SLIに採用するメトリクスの数に注意が必要。多すぎても少なすぎても重要な指標の検証が難しくなってしまうため、あらかじめCUJによって数を
絞り込んでおくことが大切。CUJに対してSLIを設定すれば、重要な機能がどれほどユーザーに提供できているかを計測することが可能。
なお、SLIはSLO（サービスレベル目標）の達成状況を測定する指標。例えば「月間の稼働率が99.00%」をSLOとして定めた場合、SLIはその値以上である必要がある。
* SLO：サービスレベル目標
** SLOは「サービスレベル目標」と呼ばれ、SLIで選定した指標が目標とする数値のこと。例えばSLIを「エラー率」に、SLOを「0.1%未満」とした場合、1000件のリクエストに対してエラーが1件もないことが目標となる。目標といっても、SLOは理想的な数値で設定するのではなく、許容可能な最低限のレベルにするのが望ましいとされる。ユーザーが不満を感じていないのであれば、必要以上にリスクを取らず、さらなる機能の開発などに注力するほうが、ビジネスの観点でよほど有益だと
考えられるため。そのため、例えば「1万件のリクエストに対してエラーが1件もない」といった、厳しい基準は求めない。なお、リスクをとれる範囲
のことを「エラーバジェット」と呼ぶが、この許容範囲をいかに有効活用できるかが、開発運用のアジリティを高めるというSREの本質であるともいえる。
SLIとSLOの関係性をまとめると、以下の表のようなイメージ。 +

SLIとSLOの関係性（例）
[cols="3,5,3", options="header"]
|===
| |SLI |SLO
|稼働率（可用性）|システムが継続して稼働可能な時間の比率 |99.00%以上
|エラー率 |ユーザーからのリクエストに対するエラーの比率 |0.1%未満のエラー率
|システムスループット |単位時間あたりに処理が可能なデータ量 |1万件/秒のリクエストを処理
|リクエストのレイテンシ（応答時間） |ユーザーからのリクエストに対して、レスポンスを返すまでにかかった時間 |平均1秒以内の応答時間
|===

* SLA：サービスレベル契約
** SLAは「サービスレベル契約」という意味で、サービス提供者と顧客の間で交わされる、サービス品質に関する契約のこと。信頼性を保つための基準を
SLIとSLOに基づいて詳細に定め、書面で締結する。SLAはサービス提供者と顧客の権利と義務を明確にするものであり、定められた基準を
満たさなかった場合には、何らかの補償が行われる場合が多くある。例えば、SLIを「エラー率」に、SLOを「0.1%未満」とした場合、1000件のリクエストに対して
エラーが1件でもあったなら、サービス提供者は顧客に対して返金などの補償を行う。もちろん、信頼性を保てないような状況が想定される場合には、
補償を行う以前から迅速に対応する必要がある。SREでは自動でSLIの監視を行い、異常があれば即座にアラートを出したり、可能な範囲で自動対応を行う仕組みを
取り入れたりする。なお、SLAはビジネス上の契約であり、SREの核はSLIとSLOにある。ただ、顧客側としてはそのサービスの可用性を測る一つの指標となるため、
サービス選定時にはSLAの確認が必須。

== SREを成功させるためのポイント

* オブザーバビリティを高める
** SREの成功には、高いオブザーバビリティの獲得が欠かせない。オブザーバビリティとは、システム上で起こった異常を通知するだけでなく、どこで何が
起こったのか、起こった理由、解決方法を把握する能力を表す指標・仕組みを指す。「Observe：観測する」と「Ability：能力」を組み合わせた、
「可観測性」を意味する言葉。SREでは、ユーザーが許容可能な範囲にサービス品質を収めつつ、高頻度で新機能の追加やサービスの改善を行い、
UXの維持と向上を図り続けている。そのためには常にシステムの全体像を把握して、内部で何が起きているのかを詳細に知っておく必要がある。
オブザーバビリティを高めることで、膨大な情報の中から必要なデータを取得し、複雑なシステムの状態を可視化することができる。エラーとして
表出した結果だけでなく、そこに至るまでの道筋をたどって原因を探り出せるため、予期せぬトラブルに対しても有効。オブザーバビリティは、SREを
実践する上で効果的な指標の計測や改善を進める強力な力となる。
* オペレーションの自動化を進める
** システムの安定稼働を実現するためには、オブザーバビリティを高めるだけでなく、そもそもミスが起こりにくい環境を作ることも大切。そのためには、
可能な限り自動化を行って手作業を減らし、ヒューマンエラーのリスクを抑える必要がある。例えば、インフラの構築と運用には、インフラ構成のコード化「IaC」が
役立つ。人手でインフラを構築しようとすると複雑な手作業が求められ、大規模になるほどエラーが起こりやすいですが、IaCを導入すればコードの実行だけで
インフラ環境を構築できるため、ヒューマンエラーの回避と迅速な環境構築が可能となる。
* 組織全体が一丸となって取り組む
** DX化が進んだ現代では、あらゆる業務の推進やサービス提供にIT技術が用いられており、システムの開発・運用体制の改善は組織の枠組みそのものを変えるほどに
重要な課題であるといえる。そのため、組織全体が一丸となってSREに取り組む体制作りは非常に重要。その試みとしては例えば、開発運用チームに対してSREの
プラクティスや文化を浸透させ、SREの動き出しをサポートする「Enabling SRE」や、SREメンバーが各プロダクト開発チームに直接入り込み、運用現場の
内情把握と実践サポートをより解像度高く行う「Embedded SRE」といったものがある。ただ、実際の現場でそういった試みが最初から行えるとは限らず、
SREがインフラエンジニアの業務やDevOpsと同じものだと誤解されることも少なくない。そのような場合でも、SREの正しい知識や考え方を組織全体で
取り入れていけるよう、根気強く啓蒙と実践を続けていくことが大切。

== SREを導入するメリット

* システムの信頼性が向上する
** SREの導入によって、システムの信頼性が向上する。各種タスクを自動化することで手作業による人的ミスや不具合の発生が抑えられるほか、SLIを
監視してシステムの状態を定量的に管理することで、異常の検知や障害への初動対応もスムーズに行えます。そのため、新機能のリリース直後に起こりやすい
トラブルにも対応可能。ダウンタイムを最小限に抑えてUXを向上させることは、ユーザーとの信頼関係を構築する上でも重要であり、SREの大きなメリットである。
* 自動化により運用が効率化される
** ログの監視など、定期的な運用作業の自動化が勧められることで、運用チームは浮いた時間をより戦略的な業務に充てることが可能。運用の仕組みを
改善すれば、さらなる効率化の好循環を生み出すことにもつながる。また、特にデプロイメントフェーズで数多く発生する細かいタスクの処理スピードを
高めることで、開発を終えたシステムを素早くリリースできるようになる。
* 運用タスクの属人化を防げる
** 運用作業の自動化に取り組む過程ではタスク内容が明確化されるため、作業品質を均一化し、属人化を防ぐことにもつながる。知らず知らずのうちに属人化が
起きていると、担当者の異動や退職・トラブル発生時に対応できず重大な損害を引き起こす恐れがあるため、気を付けなければならない。
特に重要な業務で用いているシステムではもちろんのこと、属人化を防止するには、ささいな作業手順なども誰にでもわかるかたちで整理されていることが
望ましいといえる。
* システム開発運用のアジリティを高まる
** SREでは、障害の原因分析や運用データの結果に基づき、システム開発運用プロセスの継続的な改善を行う。また、新機能を高頻度にリリースすれば、
開発チームと運用チームの関わりが密になるため、開発と運用のいずれかの都合に偏りすぎることなく、より連携のとれた強固な体制を築きやすくなる。
SREの実践によって、長期的な安定稼働と効率的な開発体制の確立に期待することが可能。このようなアジリティの高まりがSRE最大のメリットであり、
本質であるといえる。

== まとめ

システムの開発と運用の連携体制は以前から課題とされてきたが、定型作業の自動化などによって効率的な監視・運用が実現できれば、密な連携体制を整えることが可能。SREによって、システムの信頼性を高めて安定稼働を実現しながら、新機能の追加やサービスの改善を行うことができる。結果としてUXが高まり、企業競争力の
強化へつながることに期待が寄せられている。

== 参考文献
SREとは？ DevOpsとの違い、特徴、メリットをわかりやすく解説
https://www.skygroup.jp/media/article/4060/