= SREとは
:revnumber: 1.0.0
:revdate: 2026-03-11
:toc: left
:toclevels: 3
:sectnums:

https://www.skygroup.jp/media/article/4060/

SREは、サイト信頼性エンジニアリングのこと。開発担当と運用担当が連携し、システムの信頼性を高めて安定稼働を実現しながら、
新機能の追加やサービス改善を円滑に行い、UXを高めることを目指す。
現代では、信頼性と作業効率を両立したシステム開発が求められている。定型作業の自動化や各種指標の計測を行うSREの導入によって、
企業競争力のさらなる強化につながる。
運用タスクの自動化とエラーバジェットの活用により、システムの信頼性とサービスの成長の両立を実現。

== SREとDevOpsは何が違うのか

* SREの概念
** 開発と運用を組み合わせたDevOpsと混同されがちだが、両者の違いは「class SRE implements DevOps」という考え方。
これはオブジェクト指向プログラミングになぞらえた表現で、DevOpsで示された抽象的な概念を、SREで具体的に実践するという意味。
つまり、DevOpsでは開発担当と運用担当が一体化して業務の効率化を図ることを目指すのに対して、SREでは、自動化ツールで運用タスクの
処理速度を上げつつ、システムの信頼性を高めることを目指す。

== SREを実践する際に注意すべきこと

* SREの「本来の目的」を理解する
** SREには「信頼性」をシステムの重要機能の一つとして位置付けているという特徴がある。そこで信頼性を高めるために、エラーの発生を限りなくゼロに
近づけるなど、理想的な目標を設定することに固執して、かえって現場の混乱を招く結果に陥っている場合がある。
* SREの本来の目的は単純な信頼性の向上ではなく、極端に高い指標を追いかけることでもない。ユーザーが一定の満足度を得られるサービス運用を
実現しながら、開発のライフサイクルを高速化し、開発運用のアジリティを高めること。あくまでも、高すぎない目標値の下でトイルの自動化を進め、
システムの改善とサービスレベルの向上におけるトレードオフに挑むことが大切。
* このようなSREの本来の目的を踏まえつつ、サービスレベルの評価を行う必要がある。

== SREの実践に欠かせない要素

* 