= データベースセキュリティについて
:revnumber: 1.0.0
:revdate: 2026-03-11
:toc: left
:toclevels: 3
:sectnums:

== データベースセキュリティとは
データベースセキュリティとは、データベースの機密性、整合性、可用性を確立および維持するために設計された一連のツール、
制御、および対策を指す。機密性は、ほとんどのデータ侵害で損なわれる要素。

* データベースセキュリティは、以下について対処し、保護する必要がある。
** データベース内のデータ。
** データベース管理システム。
** 全ての関連アプリケーション。
** 物理データベースサーバまたは仮想データベースサーバ、およびその基盤となるハードウェア。
** データベースへのアクセスに使用されるコンピューティングまたはネットワークインフラストラクチャ。
* データベースセキュリティは、情報セキュリティのテクノロジーと実践におけるあらゆる側面を含む、複雑で困難な取り組みです。
また、データベースのユーザビリティとも当然相反する。データベースがアクセスしやすく、使いやすいものであればあるほど、セキュリティ上の脅威に対して
脆弱であり、脅威に対して安全であればあるほど、アクセスや利用が困難になります。このパラドックスはアンダーソンの法則と呼ばれる。

== 重要な理由
定義上、データ侵害とは、データベース内のデータ機密性の維持における失敗のこと。データ侵害が企業にどの程度の損害を与えるかは、様々な結果や要因に
よって異なる。

* 侵害された知的財産
** 企業秘密、発明、独自の慣行などの知的財産は、市場で競争上の優位性を維持する能力において重要な要素である場合がある。
知的財産が盗まれたり、暴露されたりした場合、競争上の優位性を維持したり回復したりすることが、困難または不可能になる場合がある。
* ブランドの評判の低下
** 顧客やパートナーは、貴社のデータや自分のデータが保護されると信頼できない場合、貴社の製品やサービスの購入に消極的となる可能性がある。
* 事業継続性（またはその欠如）
** 一部の事業は、侵害が解決されるまで営業を再開できない。
* コンプライアンス違反に対する罰金や罰則
** SAOやPCI DSSなどの世界的な規則、HIPAA法などの業界固有のデータ・プライバシー規制、あるいは、欧州の一般データ保護規則のような
地域規模のデータ・プライバシー規制の順守を怠ったことによつ財政的影響として、最悪の場合、違反一件あたり数百万ドルを超える罰金が
科される可能性がある。
* 侵害の修復および顧客への通知におけるコスト
** 侵害を受けた組織は、侵害を顧客に伝えるコストに加えて、犯罪捜査および調査活動、危機管理、トリアージ、影響を受けたシステムの修復などにかかる費用
を支払わなければなりません。

== 一般的な脅威と課題
ソフトウェアの設定ミス、脆弱性、よくある不注意や誤用が、侵害につながる場合があります。データベースセキュリティ攻撃の最も
一般的な種類または原因は以下の通り。

* 内部脅威
** 内部脅威とは、データベースへの特権アクセスを持つ次の3つのソースのいずれかによるセキュリティ脅威のこと。
*** 損害を与えようとする悪意のあるインサイダー
*** データベースを攻撃に対して脆弱にするエラーを引き起こす不注意なインサイダー
*** フィッシングなどのスキームに介して、認証情報データベース自体にアクセスし、何らかの方法で認証情報を入手する部外者。
** これらはデータベースセキュリティ侵害の最も一般的な原因であり、特権ユーザーのアクセス資格情報を
保持している従業員が多すぎた結果として生じる。
* ヒューマンエラー
** 事故、脆弱なパスワード、パスワードの共有、その他の賢明でない、または十分な情報を得ていないユーザーの行動が、
報告されたすべてのデータ侵害のほぼ半分（49%）の原因となっている。
* データベースソフトウェアの脆弱性のエクスプロイテーション
** ハッカーは、データベース管理ソフトウェアを含むあらゆる種類のソフトウェアの脆弱性を発見し、標的に
することで生計を立てている。すべての主要な商用データベース・ソフトウェア・ベンダーやオープンソース・データベース管理プラットフォームは、
これらの脆弱性に対処するため定期的にセキュリティパッチを発行していますが、これらのパッチのタイムリーな適用を
怠った場合、危険にさらされる可能性が高まる。
* SQLまたはNoSQLインジェクション攻撃
** データベース固有の脅威であり、WebアプリケーションまたはHTTPヘッダーによって提供されるデータベースクエリに、任意のSQLまたは
SQL以外の攻撃文字列を挿入することが含まれる。安全なWebアプリケーションのコーディング慣行に従わず、定期的に脆弱性テストを
実施しない組織は、これらの攻撃にさらされる可能性がある。
* バッファ・オーバーフローのエクスプロイテーション
** バッファ・オーバフローは、プロセスが保持できる範囲を超えるデータを固定長のメモリブロックに書き込もうとしたときに発生する。
攻撃者は、隣接するメモリアドレスに保管されている余分なデータを、攻撃を開始するための基盤として使用できる。
* マルウェア
** マルウェアは、脆弱性を利用したり、データベースに損害を与えたりするために特別に作成されるソフトウェアです。
マルウェアは、データベースのネットワークに接続している任意のエンドポイントを介して侵入する可能性がある。
* バックアップ攻撃
** データベース自体を保護するために使用されるものと同様にの、厳格な制御でバックアップデータを保護できない組織は、
バックアップに対する攻撃に対して脆弱である可能性がある。これらの脅威は月の要因によって悪化する。
*** データ量の増大：データのキャプチャ、ストレージ、処理は、ほぼすべての組織で指数関数的に増加し続ける。
データセキュリティツールや慣行は、近い将来及び遠い将来のニーズに対応できるよう、スケーラブルである必要がある。
*** インフラストラクチャの無秩序な拡大：特に企業がワークロードをマルチクラウドまたはハイブリッドクラウドアーキテクチャに
移行するにつれて、ネットワーク環境はますます複雑になり、セキュリティソリューションの選択、導入、管理がこれまで以上に
困難になっている。
*** 厳格化し続けている規制要件：世界的な規制コンプライアンスを取り巻く状況はますます複雑化しており、
全ての義務を遵守することがますます困難になっている。
* サービス拒否（DoS）攻撃
** サービス拒否（DoS）攻撃では、攻撃者はターゲットサーバーに多数のリクエストを大量に送り込み、サーバーは実際のユーザーからの
正当なリクエストを処理できなくなり、多くの場合、サーバーは不安定になるか、またはクラッシュする。
分散型サービス拒否攻撃（DDos）では、大量の攻撃が複数のサーバーから行われるため、攻撃の阻止がより困難になる。

== ベストプラクティス
データベースはネットワークからアクセスできるため、ネットワーク・インフラストラクチャー内またはその一部の
コンポーネントに対するセキュリティ上の脅威は、データベースに対する脅威でもあり、ユーザーのデバイスやワークステーションに影響を
与える攻撃はデータベースを脅かす可能性がある。したがって、データベースセキュリティはデータベースだけよりもはるかに
広い範囲について考慮する必要がある。
環境内のデータベースセキュリティを評価してチームの最優先事項を決定するときは、以下の各領域を考慮する。

* 物理的なセキュリティ
** データベースサーバは、オンプレミスであるか、クラウド・データセンター内にあるかに関わらず、安全な気候制御環境内に
配置する必要があります。データベースサーバがクラウド・データセンター内にある場合、クラウドプロパイダーがこれを引き受けます。
* 管理者とネットワークのアクセス制御
** 実際的な最小数のユーザーがデータベースにアクセスできるようにし、彼らの権限は、業務を行う上で必要な最小限のレベルに
制限する必要がある。同様に、ネットワークへのアクセスは、必要最小限の権限に制限する。
* ユーザーアカウントとデバイスのセキュリティ
** 誰がデータベースにアクセスしているのか、いつ、どのようにデータが使用されているのかを常に認識する。データ監視ソリューションは、
データアクティビティが異常である場合やリスクが高いと思われる場合に警告を発することができる。データベースを収容するネットワークに
接続するすべてのユーザーデバイスは、物理的にセキュア（適切なユーザーのみが扱える状態）であり、常にセキュリティ管理の対象とする。
* 暗号化
** データベース内のデータや認証データなどのすべてのデータは、保存中および転送中、最高クラスの暗号化で保護する必要がある。
全ての暗号化キーは、ベスト・プラクティス・ガイドラインに従って扱う必要がある。
* データベース・ソフトウェアのセキュリティ
** 常に最新バージョンのデータベース管理ソフトウェアを使用し、パッチが発行されたらすべてのパッチを適用する。
* アプリケーションとWebサーバーのセキュリティ
** データベースと連携するアプリケーションやWebサーバーはすべて攻撃チャネルとなる可能性があるため、継続的なセキュリティ・テストと
ベスト・プラクティスの管理の対象となる。
* バックアップのセキュリティ
** データベースのすべてのバックアップ、コピー、またはイメージは、データベース自体と同じ（または同等に厳格な）セキュリティ管理の
対象とする必要がある。
* 監査
** データベースサーバーとオペレーティングシステムへのすべてのログインを記録し、機密データに対して実行されたすべてのオペレーションを記録。
データベースのセキュリティ標準監査は、定期的に実施する必要がある。

== 管理とポリシー
ネットワーク環境全体にわたって多層的なセキュリティ制御を実装することに加えて、データベースセキュリティでは、データベース自体へのアクセスの
ための正しい制御とポリシーを確立する必要がある。それには以下が含まれる。

* データベースのインストール、変更、および構成管理を制御するための管理コントロール。
* アクセス、暗号化、トークン化、マスキングを管理するための予防制御。
* データベースアクティビティ監視およびデータ損失防止ツールを感酢するための検出制御。これらのソリューションにより、異常なアクティビティや
疑わしいアクティビティを特定して警告することができる。

データベース・セキュリティ・ポリシーは、クリティカルな知的財産の保護、サイバー・セキュリティ・ポリシー、クラウド・セキュリティ・ポリシー
などの全体的なビジネス目標と統合され、サポートされる必要がある。組織内のセキュリティ管理の維持と監査に対する責任が指定されていること、
および責任を共有する契約でクラウド・プロパイダーのポリシーが補完することを確認する。セキュリティ管理、セキュリティ・アウェアネス向上
トレーニングおよび教育プログラム、ペネトレーションテストと脆弱性評価戦略はすべて、正式なセキュリティ・ポリシーをサポートするために
確立される必要がある。

== データ保護ツールとプラットフォーム
現在、さまざまなベンダーがデータ保護ツールやプラットフォームを提供している。フルスケール・ソリューションには、次のすべての機能が
含まれている必要がある。

* 検出
** クラウドでホストされているかオンプレミスでホストされているかに関わらず、すべてのデータベースの脆弱性をスキャンして分類し、
特定された脆弱性を修復するための推奨事項を提示できるツールを探す。多くの場合、規制順守義務に準拠するため、検出機能が求められる。
* データ・アクティビティの監視
** ソリューションは、デプロイメントがオンプレミス、クラウド、またはコンテナのいずれであるかに関わらず、すべてのデータベースにおける
あらゆるデータ・アクティビティを監視および監査できる必要がある。不審なアクティビティをリアルタイムで警告することで、脅威に迅速に対応できるようにする。
また、ルール、ポリシー、職務の分離を適用でき、包括的で統一されたユーザー・インターフェースを通じてデータのステータスを可視化できる
ソリューションも必要。どのソリューションを選択しても、コンプライアンス要件を満たすために必要なレポートを生成できることを確認。
* 暗号化およびトークン化機能
** 侵害の際、暗号化は侵害に対する最終的な防御線となる。選択するツールには、オンプレミス、クラウド、ハイブリッド、または
マルチクラウド環境でデータを保護できる柔軟な暗号化機能が備わっている必要がある。トークン化（データ・マスキング）や高度な
セキュリティ・キー管理機能が必要となる場合がある業界のコンプライアンス要件に準拠した、ファイル、ボリューム、アプリケーションの
暗号化機能を備えたツールを探す。
* データセキュリティの最適化とリスク分析
** データセキュリティ情報と高度な分析を組み合わせることで、コンテキストに応じた洞察を生成できるツールにより、最適化、リスク分析、
レポート作成を簡単に実行できる。データベースのステータスとセキュリティに関する大量の履歴データと最近のデータを保持および合成
できるソリューションを選択し、網羅的でユーザーフレンドリーなセルフサービス・ダッシュボードを通じてデータ探索、監査、レポート機能を
提供するソリューションを探す。

== データベースセキュリティの主要概念

* 認証
** ユーザーがデータベースにアクセスする前に、正しい認証資格を持っていることを要求する。パスワード認証などが代表。
* 認可
** 認証されたユーザーに対して、特定リソースへのアクセスを許可・拒否する。
* アクセス制御
** ユーザーが実行できる操作の種類（読み取り、書き込み、更新、削除など）を定義。
* 暗号化
** 通信時、保管時にデータを暗号化し、不正な盗聴行為を防止。
* 監査
** データベースのアクセスログや操作ログを監視し、不審な活動やポリシー違反を検知。
* データマスキング
** 本番環境以外でデータを使う際には、機密データを隠蔽（ダミーに変える）する。
*バックアップ・リストア
** データ損失やデータ損害時に早期の回復をするためにバックアップを取得する。

== クラウドの認証
古くからデータベースの認証はパスワードが利用されてきた。
ただ、アプリケーションに何らかの形でパスワードを持たす方式は、漏洩の可能性を排除できない。
クラウドではシークレットストアを使ってパスワードを補完する。流れは以下の通り

* AppからSecrets Storeにパスワード問い合わせ。
* 許可されたAppから許可された操作だった場合、Secrets Storeはパスワードを返す。
* Appは返されたパスワードでデータベース認証を行う。

メリット：

* 開発者がパスワードを知る必要がない。
* パスワードの保護をクラウドのIAMで一元管理できる。
* 定期的なパスワード変更を容易に実装できる。
* パスワード管理をクラウドベンダーにオフロードできる。

== ネットワークの制限
データベースは機密データの集まりです。
データベースにアクセスできるアプリケーション、ユーザーをネットワーク的に制限する。

== 最小権限の原則
DBMSの権限では、どのテーブルに対してどの操作（INSERT、DELETE、UPDATAなど）を許可するか、という設定を行う。
この権限設定は難しいので、アプリケーションユーザーに強い権限（全テーブルに全操作OK）を付与してしまうことがあるが、アンチパターン。
必要な権限だけを付与するようにする。

== セキュリティパッチの適用
セキュリティパッチは、ソフトウェアやシステムのセキュリティ上の脆弱性を修正するアップデート。
セキュリティパッチを定期的に適用することは、サイバーセキュリティ戦略の基本的かつ重要な部分であり、攻撃者が
システムを侵害する手段を最小限に抑えるために必須の習慣。
そのためには、セキュリティパッチがリリースされ次第、迅速に適用することが勧められる。
また、それらの適用を継続的に監視し、セキュリティ対策を最新の状態に保つためのパッチ管理ポリシーを確立することが重要。
クラウドベンダーのマネージドデータベースを使っている場合、セキュリティパッチはクラウドベンダーによって管理される。
適用の内容やタイミングは事前に通知される。その通知を見て適用タイミングを決定し、決行する。
セキュリティパッチはデータベースクライアント（アプリケーションなど）にも提供されるケースがある。
その際には、データベースクライアントにも同じように適用する。

== SQLインジェクション
SQLインジェクションは、アプリケーションの脆弱性をついて不正なSQL文を混入させ、本来アクセスできないはずのデータにアクセスし、
内部侵入する攻撃手法。

* SQLインジェクションの対策
** SQL文の組み立ては全てプレースホルダで実装する。
** SQL文の組み立てを文字列連結により行う場合は、エスケープ処理等を行うデータベースエンジンのAPIを用いて
SQL文のリテラルを正しく構成する。
** ウェブアプリケーションに渡されるパラメータにSQL文を直接指定しない。
** SQLインジェクションに対応したフレームワークを使う。
** 前段のロードバランサー等にWAFを設置する。